### ISSUE TITLE
Erratum: spelling error p. 119

### ISSUE THREAD

**Issue by wpetry** [ipmbook/first-edition#1]
Page 119, figure 5.5: _Artemisia_ is misspelled as _Artemesia_ in both panel A & the figure legend

Taxonomic name reference: http://www.tropicos.org/Name/2701816

**Comment by ellner** [comment]
Thanks, Will. I don't know how many times I've made that mistake. I will add this to the Errata file. Artemis. It's named after Artemis. How hard is that to remember?
